Added demo binary

diff --git a/scripts/run.sh.in b/scripts/run.sh.in
--- a/scripts/run.sh.in
+++ b/scripts/run.sh.in
@@ -7,27 +7,47 @@
 # Runs on the server, in the directory deploy.sh synced to.
 
 module="sc-@SC_DEPLOY_NAME@"
+version="@SC_VERSION@"
 ubuntu_codename=$(lsb_release -sc)
 build_directory="cmake-build-$ubuntu_codename"
 apt -y install cmake clang-tidy ccache g++
 
 pushd "/var/www/build/$module" || exit
+
+if [ -f pre-build.sh ]; then
+    echo "Running pre-build"
+else
+    echo "No pre-build required"
+fi
+
 cmake -DCMAKE_BUILD_TYPE=Release -B $build_directory -S . || exit
 cmake --build $build_directory -j 12 || exit
 ctest --test-dir $build_directory --output-on-failure || exit
 cmake --install $build_directory
+
 pushd $build_directory || exit
 rm -rf *.deb
 cpack --config CPackConfig.cmake -G DEB
 rm -rf *unknown*.deb
-rm -rf /var/www/build/repo/pool/$ubuntu_codename/*.deb
-rsync -av *.deb /var/www/build/repo/pool/$ubuntu_codename/
-rm -rf /var/www/build/repo/pool/$ubuntu_codename/*unknown*
+rsync -av *.deb /var/www/build/debs/
+rm -rf /var/www/build/debs/*unknown*
+popd || exit
+
+debfile="${module/sc-/simply-cpp-}"
+debfile="${debfile/-cpp-core/-cpp}"
+echo "Updating repository $debfile $version"
+pushd /var/www/build/repo || exit
 export GNUPGHOME=/var/www/build/signing
-# reprepro remove noble ...
-# reprepro clearvanished
-reprepro -b /var/www/build/repo includedeb $ubuntu_codename /var/www/build/repo/pool/$ubuntu_codename/*.deb
-# reprepro -b /var/www/build/repo includedeb $ubuntu_codename *.deb
+reprepro remove $ubuntu_codename $debfile
+reprepro remove $ubuntu_codename $debfile-dev
+reprepro list $ubuntu_codename
+for deb in ../debs/*.deb; do
+    [ -f "$deb" ] || continue
+    echo "Loading $deb"
+    reprepro includedeb $ubuntu_codename "$deb"
+    # mv "$deb" processed/
+done
+reprepro list $ubuntu_codename
 popd || exit
 
 popd || exit
